#!/usr/bin/env node

/**
 * Setup script for 50-Minute MVP Template
 * Automates initial project configuration
 */

const fs = require('fs')
const { execFileSync } = require('child_process')
const readline = require('readline')

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
})

function question(query) {
  return new Promise((resolve) => rl.question(query, resolve))
}

function exec(command, args = [], options = {}) {
  try {
    return execFileSync(command, args, { stdio: 'inherit', encoding: 'utf8', ...options })
  } catch (error) {
    console.error(`Failed to execute: ${command} ${args.join(' ')}`)
    throw error
  }
}

async function main() {
  console.log('\n🚀 50-Minute MVP Template Setup\n')

  // Check if .env.local exists
  if (fs.existsSync('.env.local')) {
    const overwrite = await question(
      '.env.local already exists. Overwrite? (y/N): '
    )
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Setup cancelled.')
      rl.close()
      return
    }
  }

  console.log('\n📋 Step 1: Database Setup')
  console.log('Choose your database:')
  console.log('1. Turso (Recommended - SQLite at the edge)')
  console.log('2. I have my own Turso database')

  const dbChoice = await question('Choice (1/2): ')

  let tursoUrl, tursoToken

  if (dbChoice === '1') {
    console.log('\nSetting up Turso database...')

    // Check if Turso CLI is installed
    try {
      exec('turso', ['--version'], { stdio: 'ignore' })
    } catch {
      console.log('\n⚠️  Turso CLI not found. Installing...')
      console.log('\nRun this command:')
      console.log('curl -sSfL https://get.tur.so/install.sh | bash')
      console.log('\nThen run this setup script again.')
      rl.close()
      return
    }

    const dbName = await question('Database name (default: my-mvp-db): ')
    const finalDbName = dbName || 'my-mvp-db'

    console.log(`\nCreating database: ${finalDbName}...`)

    try {
      exec('turso', ['db', 'create', finalDbName])
      tursoUrl = exec('turso', ['db', 'show', finalDbName, '--url'], { stdio: 'pipe' }).trim()
      tursoToken = exec('turso', ['db', 'tokens', 'create', finalDbName], { stdio: 'pipe' }).trim()

      console.log('✅ Database created successfully!')
    } catch (error) {
      console.error('❌ Failed to create database')
      rl.close()
      return
    }
  } else {
    tursoUrl = await question('Turso Database URL: ')
    tursoToken = await question('Turso Auth Token: ')
  }

  console.log('\n🔐 Step 2: Authentication Setup (Clerk)')
  console.log('Get your keys from: https://dashboard.clerk.com')

  const clerkPubKey = await question('Clerk Publishable Key: ')
  const clerkSecretKey = await question('Clerk Secret Key: ')

  console.log('\n📧 Step 3: Email Setup (Resend - Optional)')
  const setupEmail = await question('Set up email? (y/N): ')

  let resendKey = ''
  if (setupEmail.toLowerCase() === 'y') {
    console.log('Get your key from: https://resend.com/api-keys')
    resendKey = await question('Resend API Key: ')
  }

  // Write .env.local
  const envContent = `# Auto-generated by setup script

# Clerk Authentication
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${clerkPubKey}
CLERK_SECRET_KEY=${clerkSecretKey}

# Turso Database
TURSO_DATABASE_URL=${tursoUrl}
TURSO_AUTH_TOKEN=${tursoToken}

${resendKey ? `# Resend Email\nRESEND_API_KEY=${resendKey}\n` : ''}
# App URL
NEXT_PUBLIC_URL=http://localhost:3000
`

  fs.writeFileSync('.env.local', envContent)
  console.log('\n✅ .env.local created!')

  console.log('\n📊 Step 4: Database Schema')
  const pushSchema = await question('Push database schema now? (Y/n): ')

  if (pushSchema.toLowerCase() !== 'n') {
    console.log('\nPushing schema...')
    try {
      exec('npm', ['run', 'db:push'])
      console.log('✅ Schema pushed successfully!')
    } catch {
      console.log('⚠️  Failed to push schema. Run manually: npm run db:push')
    }
  }

  console.log('\n🎉 Setup complete!\n')
  console.log('Next steps:')
  console.log('1. npm run dev          # Start development server')
  console.log('2. npm test             # Run tests')
  console.log('3. vercel --prod        # Deploy to production\n')

  rl.close()
}

main().catch((error) => {
  console.error('Setup failed:', error)
  rl.close()
  process.exit(1)
})
